// generated by terraform (infra/envs/dev/frontend.tf) -- not committed,
// re-run `terraform apply` if this is missing or stale
window.MONTAGE_CONFIG = {
  apiBaseUrl: "${api_base_url}",
  cognitoDomain: "${cognito_domain}",
  cognitoClientId: "${cognito_client_id}",
};
